
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'
export const GET_PRICE_QUOTE_REQUEST = 'GET_PRICE_QUOTE_REQUEST'
export const GET_PRICE_QUOTE_SUCCESS = 'GET_PRICE_QUOTE_SUCCESS'
export const GET_PRICE_QUOTE_FAILURE = 'GET_PRICE_QUOTE_FAILURE'
